### ISSUE TITLE
Determine weekly class structure

### ISSUE THREAD

**Issue by jesse-stew** [crowjm/portfolio-class#2]
1. Determine who's going to teach what so that issues can be assigned
2. Together, think about the goals we want to accomplish for each week, homework to supplement, how each goal might be best taught and a rough timebox for class schedule.

**Comment by dawndelatte** [comment]
Hey Jesse, so I wanted to leave some thoughts here on teaching structure and see what you think. To me, I think there are two ways we could go about it.
1. We divide the classes (2 each), and trade between teaching and TA. This will give a varied perspective but possibly some inconsistency–as far as teaching style goes, you certainly have more experience? I would be more comfortable with design/visual related stuff (design/ideation and CSS). A "con" I have for this (personally) is a heavier work load for us individually (which I'm wary of considering the start of a new job, and both of us being out of town/visiting fam this month). 
2. We divide subjects/concepts up and double team each class. I like the idea of this structure, I think it could make it more fun and interactive. We could trade off TA'ing and maybe have some other TA's come in? But having two people knowing the structure/curriculum could help with questions and consistency. A "con" I see for this one would be needing a lot of planning and coordination to keep it seamless for the students (but this will need to happen for either route anyway). An idea for this could be trading off lecture and workshop perhaps? 

Again, these are just a few thoughts. I think it will be easier to set goals and structure and homework once we decide how we're going to go about teaching it. What are your thoughts/concerns about the teaching structure?

**Comment by jesse-stew** [comment]
@dawndelatte, totally agree; like I mentioned on Slack, we need to figure out how to divvy up the work before we can move forward.💃 ✨ 

My initial thoughts:
Given time restraints, I think we should divide the classes and therefore divide the roles of leading and supporting. I'm not sure if it would be a 2/2 split since the last week is going to be a little bit of Github (checking out to gh-pages and pushing) and then open for questions, small demos on things they can do next, more in-depth Ps perhaps?, etc–which lends itself to co-teaching. 

If this is the way we go, it's critical that we get feedback from each other along the way on slides, demos, how to best teach concepts, homework, everything, and that we get together once before each class so that the lead teacher for that class can practice. This way we both know the structure and what to expect.

In a perfect world, I would like to co-teach all the classes, but given time, I'm worried about how well we would be able to execute on that for this 4 week class.

**Comment by jesse-stew** [comment]
@dawndelatte 

A suggested breakdown:
Week 1: Dawn leads, Jesse supports
Week 2: Jesse leads, Dawn supports
Week 3: We're really covering 2 concepts here, CSS & RWD, so there's potential for co-teaching
Week 4: co-teach

**Comment by jesse-stew** [comment]
I've also already got some slides and demos for HTML, CSS, and RWD from classes I've taught in the past that could be useful.

**Comment by dawndelatte** [comment]
@crowjm I think that the above teacher structure will be good. Let's think about how we might co-teach week 3's class. If I had to guess, it will be pretty code heavy. Students tend to need more time with CSS I think (plus the media queries). Maybe I could do a brief overview of some responsive design principles/thinking, before jumping into building out the media queries? It may not need to be a separate thing though. What are your thoughts?

**Comment by jesse-stew** [comment]
@dawndelatte I was thinking it would be split between CSS basics and RWD background/principles/how to write a media query (and how to override styles). Thoughts?

**Comment by dawndelatte** [comment]
@crowjm I think that split is good. The only area I find the "split" a little complicated would be layout and spacing (does that go with CSS basics or RWD?). So I think we could start with CSS basics to tie back into the basic design stuff (color, type, etc.) and then go into more complicated code concepts with layout and media queries. The idea of RWD is not so complicated, so I don't know if it needs an overview by itself like I suggested. I think the learning will come more with seeing how to manipulate the content with code. Do you have a preference on what to teach? I think I would like to do the CSS basics. With your experience and expertise, I feel like RWD and media queries will be better from you. What do you think? Also, what do you think about having one slide deck for this, to make the process more streamlined and seamless?
