### ISSUE TITLE
Gather resources

### ISSUE THREAD

**Issue by jesse-stew** [crowjm/portfolio-class#8]
Find resources to send out for:
- (possibly) before class
- supporting materials for each weekly topics

**Comment by jesse-stew** [comment]
Supporting Material for Week 2:
- https://developer.mozilla.org/en-US/docs/Web/HTML
- http://www.htmldog.com/references/html/tags/
- http://alistapart.com/blog/post/overwhelmed-by-code
- also make sure they have access to a pdf of the slides

**Comment by dawndelatte** [comment]
Supporting Materials for Week 1:
- [Awwwards.com for inspiration on layout and color](http://www.awwwards.com/websites/portfolio/) - I'm debating on this one
- [Colour Lovers - Web](http://www.colourlovers.com/web/)
- [Browser Colors](http://www.colors.commutercreative.com/grid/)
- [Typekit - for Abode users](https://typekit.com/fonts)
- [Google Fonts](https://fonts.google.com/)
- [Style Tiles by Samantha Warren](http://styletil.es/)
- PDF of slides

**Comment by jesse-stew** [comment]
Supporting Materials for Week 3:
- [CSS Tricks](https://css-tricks.com/)
- [Responsive Web Design](http://alistapart.com/article/responsive-web-design)
- [Google Fonts](http://fonts.google.com) 
- [Media Query Demo](http://codepen.io/crowjm/pen/GqYYvx)
- [Floats Demo](http://codepen.io/crowjm/pen/VjEEKb)
- also make sure students have access to a pdf of the slides

**Comment by dawndelatte** [comment]
Bonus homework articles – Week 1:
- [Content Strategy and Usability](https://www.usability.gov/what-and-why/content-strategy.html)
- [Planning Your Web Design with Sketches](http://tympanus.net/codrops/2013/01/29/planning-your-web-design-with-sketches/)
- [The Meaning of Color](https://www.smashingmagazine.com/2010/01/color-theory-for-designers-part-1-the-meaning-of-color/)
- [Colors in Cultures](http://www.informationisbeautiful.net/visualizations/colours-in-cultures/)

**Comment by dawndelatte** [comment]
@crowjm ^ Do you think this is a good mix/relevant? Let me know if you think there's anything else. I will also provide them with any links we use during class ("supporting materials").

**Comment by jesse-stew** [comment]
@dawndelatte 🚀
